#!/bin/bash

workspaces()
{
	echo $(hyprctl workspaces -j | jq 'sort_by(.id)')
}

workspaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
workspaces
done
